CREATE TABLE Usuario (
	UsuarioId INT NOT NULL IDENTITY PRIMARY KEY,
	Nome VARCHAR(60) NOT NULL,
	Email VARCHAR(80) NOT NULL,
	Senha VARCHAR(32) NOT NULL
);

CREATE TABLE Pessoa (
	PessoaId INT NOT NULL IDENTITY PRIMARY KEY,
	UsuarioId INT NOT NULL,
	Nome VARCHAR(60) NOT NULL,
	Sobrenome VARCHAR(60),
	Cpf VARCHAR(11),
	Telefone VARCHAR(11),
	Email VARCHAR(80),
	Excluido BIT NOT NULL DEFAULT 0,
	
	FOREIGN KEY(UsuarioId) REFERENCES Usuario (UsuarioId)
);

CREATE TABLE Endereco (
	EnderecoId INT NOT NULL IDENTITY PRIMARY KEY,
	Logradouro VARCHAR(80) NOT NULL,
	Numero VARCHAR(10),
	Bairro VARCHAR(60) NOT NULL,
	Municipio VARCHAR(80) NOT NULL,
	UF CHAR(2) NOT NULL,
	Cep VARCHAR(10) NOT NULL
);

CREATE TABLE PessoaEndereco (
	PessoaEnderecoId INT NOT NULL IDENTITY PRIMARY KEY,
	PessoaId INT NOT NULL,
	EnderecoId INT NOT NULL,
	Excluido BIT NOT NULL DEFAULT 0,

	FOREIGN KEY(PessoaId) REFERENCES Pessoa (PessoaId),
	FOREIGN KEY(EnderecoId) REFERENCES Endereco (EnderecoId)
);

CREATE TABLE Jogo (
	JogoId INT NOT NULL IDENTITY PRIMARY KEY,
	UsuarioId INT NOT NULL,
	Nome VARCHAR(150) NOT NULL,
	Excluido BIT NOT NULL DEFAULT 0,

	FOREIGN KEY(UsuarioId) REFERENCES Usuario (UsuarioId)
);

CREATE TABLE Emprestimo (
	EmprestimoId INT NOT NULL IDENTITY PRIMARY KEY,
	PessoaId INT NOT NULL,
	JogoId INT NOT NULL,
	UsuarioId INT NOT NULL,
	DataHora DATETIME NOT NULL,

	FOREIGN KEY(PessoaId) REFERENCES Pessoa (PessoaId),
	FOREIGN KEY(JogoId) REFERENCES Jogo (JogoId),
	FOREIGN KEY(UsuarioId) REFERENCES Usuario (UsuarioId)
);

CREATE TABLE Devolucao (
	DevolucaoId INT NOT NULL IDENTITY PRIMARY KEY,
	EmprestimoId INT NOT NULL,
	UsuarioId INT NOT NULL,
	DataHora DATETIME NOT NULL,
	Avaliacao TINYINT NOT NULL,

	FOREIGN KEY(EmprestimoId) REFERENCES Emprestimo (EmprestimoId),
	FOREIGN KEY(UsuarioId) REFERENCES Usuario (UsuarioId)
);